site_name: Genotype Imputation
site_author: Genomics Aotearoa
site_dir: public
site_url: "https://genomicsaotearoa.github.io/Imputation-workshop/"

#Repository information

repo_name:   GenomicsAotearoa/Imputation-workshop
repo_url: https://github.com/GenomicsAotearoa/Imputation-workshop


theme:
  name: material
  logo: ../theme_figures/nesi_ga.png
  favicon: ../theme_figures/nesi_ga.png
   # 404 page
  static_templates:
    - 404.html

  palette:

  # Palette toggle for automatic mode
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
    primary: custom

  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: custom


    toggle:
      icon: material/brightness-7
      name: Switch to dark mode

  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to system preference
    primary: custom
  
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - content.code.copy
    - content.code.annotate

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Mukta
    code: Roboto Mono

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.pathconverter

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


plugins: 
  - glightbox:
      effect: zoom
      zoomable: true
  - search:
      lang: en
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true

copyright : Pangenome Graphs workshop material is licensed under a <a rel="noopener" target="_blank" href="https://www.apache.org/licenses/LICENSE-2.0">APACHE LICENSE, VERSION 2.0</a>


extra_css:
  - stylesheets/extra.css
